include:
  - project: 'DevOps/pipelines/docker-build'
    ref: master
    file: '/.gitlab-ci.yml'

release-image-version:
  stage: release
  script:
    - export CONTAINER_VERSION_IMAGE=${CI_REGISTRY_IMAGE}:${CONTAINER_TAG_PREFIX}${CI_COMMIT_TAG}${CONTAINER_TAG_SUFFIX}
    - docker pull $CONTAINER_TEST_IMAGE || true
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_VERSION_IMAGE
    - docker push $CONTAINER_VERSION_IMAGE
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
